"""Litube ↔ 3proxy integration: cfg generator, per-user allocation, SIGHUP-safe reload.

3proxy is run inside its own docker container with network_mode=host, so it
binds VPS public IP on 11001 (SOCKS5) and 11002 (HTTP CONNECT). Each user is
a 3proxy `users X:CL:password` line and authenticates on whichever port they
hit. On signup / ban / revoke, we regenerate the cfg (one HTTP CONNECT and
one SOCKS5 listener block, plus all current users) and SIGHUP the parent
process so it re-reads the cfg without dropping existing connections.
"""
from __future__ import annotations

import asyncio
import logging
import os
import secrets
import signal
from datetime import datetime, timedelta, timezone
from pathlib import Path

from fastapi import HTTPException

from . import db

logger = logging.getLogger("litetube.3proxy")

CFG_PATH = os.environ.get("THREEPROXY_CFG_PATH", "/var/lib/3proxy/3proxy.cfg")
PID_PATH = os.environ.get("THREEPROXY_PID_PATH", "/var/lib/3proxy/3proxy.pid")
SOCKS_PORT = int(os.environ.get("THREEPROXY_SOCKS5_PORT", "11001"))
HTTP_PORT = int(os.environ.get("THREEPROXY_HTTP_PORT", "11002"))
PROXY_HOST = os.environ.get("PROXY_HOST", "82.202.141.81")


# Pending user add/revoke queue drained by reload_worker.
_pending: asyncio.Queue | None = None
_lock: asyncio.Lock | None = None


def bootstrap() -> None:
    """Ensure base directory exists with permissive mode for 3proxy writer."""
    Path(CFG_PATH).parent.mkdir(parents=True, exist_ok=True)
    try:
        Path(PID_PATH).touch(exist_ok=True)
    except Exception:
        pass


async def _ensure_async_runtime():
    global _pending, _lock
    if _pending is None:
        _pending = asyncio.Queue()
    if _lock is None:
        _lock = asyncio.Lock()


# ---- per-user allocation ----------------------------------------

async def allocate_proxy_for_user(user_id: int) -> None:
    """Create proxy+api_token records, push 'user_add' to reload queue."""
    await _ensure_async_runtime()
    uid = secrets.token_urlsafe(16)
    auth_token = secrets.token_urlsafe(24)
    now = await db.now()
    await db.conn().execute(
        "INSERT INTO proxies(uid,host,port,type,auth_token,is_active,owner_user_id,is_alive,latency_ms,last_check_at,failed_count,created_at,updated_at) "
        "VALUES (?,?,?,?,?,1,?,1,0,NULL,0,?,?)",
        (uid, PROXY_HOST, SOCKS_PORT, "socks5http", auth_token,
         user_id, now, now))
    exp = (datetime.now(timezone.utc) + timedelta(days=90)).strftime("%Y-%m-%dT%H:%M:%SZ")
    await db.conn().execute(
        "INSERT INTO api_tokens(user_id,token,expires_at,created_at) "
        "VALUES (?,?,?,?)",
        (user_id, auth_token, exp, now))
    await _pending.put({"kind": "user_add", "uid": uid, "login": uid, "password": auth_token})


async def revoke_user_proxy(user_id: int) -> None:
    await _ensure_async_runtime()
    rows = await db.conn().fetch_all("SELECT uid FROM proxies WHERE owner_user_id=?", (user_id,))
    for r in rows:
        await _pending.put({"kind": "user_remove", "uid": r["uid"]})
    await db.conn().execute(
        "UPDATE proxies SET is_active=0 WHERE owner_user_id=?", (user_id,))


# ---- cfg generator ---------------

def render_cfg(users: list[dict]) -> str:
    """Render 3proxy.cfg from current non-banned user list."""
    lines = [
        "#!/usr/local/3proxy/bin/3proxy",
        "# Generated by Litetube — do not hand-edit. Reload via SIGHUP.",
        "daemon",
        "pidfile /var/lib/3proxy/3proxy.pid",
        "nscache 65536",
        "nserver 8.8.8.8",
        "nserver 1.1.1.1",
        "log /var/log/3proxy/3proxy.log D",
        "logformat \"- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T\"",
        "rotate 30",
        "maxconn 32768",
        "stacksize 65536",
        "flush",
        "",
        "auth strong",
        "# No 'allow' directive -- 'auth strong' + the 'users' line is sufficient.",
        "",
        "external 0.0.0.0",
        "internal 0.0.0.0",
        "",
        "flush",
        f"socks -p{SOCKS_PORT} -i0.0.0.0 -e0.0.0.0",
        "",
        "flush",
        f"proxy -p{HTTP_PORT} -i0.0.0.0 -e0.0.0.0",
        "",
        "flush",
    ]
    if not users:
        # 'auth strong' requires a non-empty 'users' line; 3proxy 0.9.x
        # refuses to start with an empty cleartext password. Generate a
        # fresh random unguessable dummy per render so the literal in git
        # is never the one running in /var/lib/3proxy/3proxy.cfg.
        dummy = secrets.token_hex(16)
        lines.append(f'users nobody:CL:{dummy}')
    else:
        for u in users:
            lines.append(f'users {u["login"]}:CL:{u["password"]}')
    lines.append("")
    return "\n".join(lines)


# ---- SIGHUP-safe reload worker ---------------

async def _render_active_users() -> list[dict]:
    rows = await db.conn().fetch_all(
        "SELECT p.uid, p.auth_token FROM proxies p "
        "JOIN users u ON u.id = p.owner_user_id "
        "WHERE p.is_active=1 AND u.status IN ('trial','active')")
    return [{"login": r["uid"], "password": r["auth_token"]} for r in rows]


async def _write_cfg_and_sighup(active_users: list[dict]) -> None:
    cfg_text = render_cfg(active_users)
    Path(CFG_PATH).write_text(cfg_text, encoding="utf-8")
    Path(CFG_PATH).chmod(0o644)
    logger.info("wrote 3proxy.cfg with %d users", len(active_users))
    # SIGHUP parent 3proxy process to re-read.
    try:
        pid_text = Path(PID_PATH).read_text().strip()
        pid = int(pid_text)
    except (FileNotFoundError, ValueError):
        logger.warning("no 3proxy pid file %s; supervisord will re-read on next lifecycle", PID_PATH)
        return
    try:
        os.kill(pid, signal.SIGHUP)
        logger.info("SIGHUP sent to 3proxy pid=%d", pid)
    except ProcessLookupError:
        logger.warning("3proxy pid=%d not running; will be restarted by supervisor", pid)
    except PermissionError:
        logger.error("permission denied sending SIGHUP to %d", pid)


async def reload_worker():
    """Drain pending changes, coalesce for ~200ms, then render+SIGHUP.

    On hard failure (cfg write error, SIGHUP denied, etc.), re-enqueue the
    failed batch atomically so subsequent ticks re-attempt.
    """
    await _ensure_async_runtime()
    while True:
        try:
            change = await _pending.get()
            batch = [change]
            try:
                while True:
                    nxt = await asyncio.wait_for(_pending.get(), timeout=0.2)
                    batch.append(nxt)
            except asyncio.TimeoutError:
                pass
            async with _lock:
                active = await _render_active_users()
                try:
                    await _write_cfg_and_sighup(active)
                except Exception:
                    for c in batch:
                        try:
                            _pending.put_nowait(c)
                        except Exception:
                            pass
                    raise
        except asyncio.CancelledError:
            break
        except Exception:
            logger.exception("reload worker error")


# ---- /proxy/refresh -----------------------------------------------

async def refresh_token(creds: dict) -> dict:
    user_id = creds["user_id"]
    row = await db.conn().fetch_one(
        "SELECT * FROM proxies WHERE owner_user_id=? AND is_active=1 LIMIT 1",
        (user_id,))
    if not row:
        raise HTTPException(404, "no_proxy_assigned")
    if not row["is_alive"]:
        raise HTTPException(503, "proxy_temp_offline")
    return {
        "host": row["host"],
        "port": row["port"],
        "uid": row["uid"],
        "type": row["type"],
        "scheme": row["type"],
        "login": row["uid"],
        "password": row["auth_token"],
        "ttl_seconds": 600,
    }


async def list_all_proxies() -> list:
    rows = await db.conn().fetch_all(
        "SELECT p.*, u.email FROM proxies p LEFT JOIN users u ON u.id=p.owner_user_id "
        "ORDER BY p.created_at DESC")
    return [dict(r) for r in rows]


# ---- /api/proxy/pool (TV client) ----------------------------------
#
# Returns up to N proxies suitable for the calling device, ordered by
# is_alive DESC, latency_ms ASC. Currently the user's single 3proxy
# allocation; future shared fallback rows can be appended.
PROXY_POOL_SIZE = int(os.environ.get("PROXY_POOL_SIZE", "3"))


def _serialize_proxy(row) -> dict:
    """Build a /api/proxy/pool entry. Mirrors the PasswdURI shape so the TV
    client can drop it into the existing PasswdURI parser unchanged."""
    return {
        "host": row["host"],
        "port": row["port"],
        "type": row["type"],
        "scheme": row["type"],
        "login": row["uid"],
        "password": row["auth_token"],
        "uid": row["uid"],
        "latency_ms": row["latency_ms"],
    }


async def proxy_pool(creds: dict) -> list:
    """Return the user's proxy pool, ordered by is_alive DESC + latency ASC."""
    user_id = creds["user_id"]
    rows = await db.conn().fetch_all(
        "SELECT * FROM proxies WHERE owner_user_id=? AND is_active=1 "
        "ORDER BY is_alive DESC, latency_ms ASC LIMIT ?",
        (user_id, PROXY_POOL_SIZE))
    if not rows:
        raise HTTPException(404, "no_proxy_assigned")
    return [_serialize_proxy(r) for r in rows]
